[package]
name = "chip8r"
version = "0.1.0"
authors = ["Jeff <jeffciesielski@gmail.com>"]

[dependencies]

rand = "0.3.16"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["ttf","image","gfx","mixer"]
